apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Elesh75/JenkinsRunner.git
    targetRevision: Devv # or specify the Git branch/tag/commit you want to deploy
    path: Dev
  destination:
    server: https://kubernetes.default.svc  # The address of your Kubernetes cluster
    namespace: my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true  # Set to true to delete resources not defined in the source
      selfHeal: true  # Set to true to automatically apply changes detected by ArgoCD
