apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
     app: my-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-demo
  template:
    metadata:
      labels:
        app: my-demo
    spec:
      containers:
      - name: app
        image: mylandmarktech/spring-boot-mongo:latest
        resources: {}
    status: {}