apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["appprojects"]
  verbs: ["list", "get"]  # Adjust verbs based on your needs

---
# Cluster role Binding

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo-cd
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-role  # Use the name of the ClusterRole you defined
  apiGroup: rbac.authorization.k8s.io
