apiVersion: v1
kind: Service
metadata:  
  name: pipeline-service
spec:
  selector:    
    app: my-demo
  type: NodePort
  ports:  
  - name: http
    port: 8032
    targetPort: 8080
    protocol: TCP